### ISSUE TITLE
Ability to add the user-agent in the report too

### ISSUE THREAD

**Issue by girlbossceo** [pistasjis/ListenCaddy#11]
Sometimes I get hits from bad IPs with suspicious or weird user agents, or even just scanning user-agents in general. Would be nice to have the ability to add the user-agent in the report message too.

(hope you're still interested in maintaining this project, I use it a lot :P)

**Comment by pistasjis** [comment]
Hey, sorry for not responding (I don't get notifications from GitHub for some reason, and I've just started school). I don't maintan the project that much because there isn't much left to do, and this is pretty easy to implement so I'll do it.

**Comment by girlbossceo** [comment]
No worries! As long as you still acknowledge the project and are still open to feature requests and merging PRs like dependency updates, that's good enough for me :>

**Comment by pistasjis** [comment]
![image](https://github.com/pistasjis/ListenCaddy/assets/57069715/75abc622-d413-455c-aae8-bd872fb09007)

Implemented. I'll also update dependencies while we're at it.
